spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  datasource:
    url: jdbc:mysql://localhost:3306/mypage # 사용하는 데이터베이스에 맞게 변경
    driver-class-name: com.mysql.cj.jdbc.Driver # 사용하는 데이터베이스에 맞게 변경
    username: weather # 사용하는 데이터베이스에 맞게 변경
    password: 1234 # 사용하는 데이터베이스에 맞게 변경

  jpa:
    hibernate:
      ddl-auto: none # create, update, validate, none 중 선택
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL # 사용하는 데이터베이스에 맞게 변경
        format_sql: true # SQL 문을 보기 좋게 포맷팅
    show-sql: true # 콘솔에 SQL 문 출력