spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
  datasource:
    url: jdbc:h2:mem:testdb # 사용하는 데이터베이스에 맞게 변경
    driver-class-name: org.h2.Driver # 사용하는 데이터베이스에 맞게 변경
    username: sa # 사용하는 데이터베이스에 맞게 변경
    password: # 사용하는 데이터베이스에 맞게 변경

  jpa:
    hibernate:
      ddl-auto: create # create, update, validate, none 중 선택
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL # 사용하는 데이터베이스에 맞게 변경
        format_sql: true # SQL 문을 보기 좋게 포맷팅
    show-sql: true # 콘솔에 SQL 문 출력